### ISSUE TITLE
Payload Invalid on NULL value

### ISSUE THREAD

**Issue by JaySephone** [gregoryduckworth/Encryptable#2]
Hello, I noticed an issue when the encryptable trait attempts to decrypt a cell in a database that is set to ```NULL```. I looked at the source code and also noticed that it is checking for, explicitly, an empty string. Perhaps trying a ```!empty($value)``` would work better?

```
$value = parent::getAttribute($key);
        if (in_array($key, $this->encryptable) && !empty($value)) {
            $value = decrypt($value);

        }
```

**Comment by gregoryduckworth** [comment]
Yeah! You are absolutely right, I haven't touched this in a while. Should be fixed in [1.0.2](https://github.com/gregoryduckworth/Encryptable/releases/tag/1.0.2)
